name: Build NixOS and Push to Cachix

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        host: [ acer, nixos, nvidia, steam, umka ]

    steps:
      - uses: actions/checkout@v4

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable-small

      - uses: cachix/cachix-action@v17
        with:
          name: proxyvt
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build and push ${{ matrix.host }}
        run: |
          cachix watch-exec proxyvt -- nix build .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel --keep-going
